routes/web.php
<?php

Route::get('/', function () {
    return view('welcome');
});

Route::get('admin/login', 'Admin\Auth\LoginController@showLoginForm')->name('admin.login');
Route::post('admin/login', 'Admin\Auth\LoginController@login');

Route::group(
    [
        'prefix'     => 'admin',
        'as'         => 'admin.',
        'namespace'  => 'Admin',
        'middleware' => [
            'auth',
            'can:admin-panel'
        ],
    ],
    function () {

        Route::get('/', 'DashboardController@index')->name('dashboard');

        Route::post('logout', 'Auth\LoginController@logout')->name('logout');

        // Route::resource('user', 'UserController')->name('index', 'user');
        Route::resource('user', 'Users\UserController')->name('index', 'user');
        Route::resource('page', 'Pages\PageController')->name('index', 'page');
        Route::resource('category', 'Catalog\CategoryController')->name('index', 'category');
        Route::resource('product', 'Catalog\ProductController')->name('index', 'product');
        Route::resource('certificate', 'Certificates\CertificateController')->name('index', 'certificate');


        Route::resource('files', 'Common\FileController')->name('index', 'files');

        //Route::get('files/create', 'Common\FileController@create')->name('files.create');
        //Route::post('files/create', 'Common\FileController@store')->name('files.store');
        //Route::get('files/{id}/edit', 'Common\FileController@edit')->name('files.edit');
        //Route::post('files/{id}/edit', 'Common\FileController@update')->name('files.update');


        //Route::post('files/create', 'Common\FileController@store')->name('store', 'files');

        //Route::get('files', 'Common\FileController@index')->name('files.list');
        //Route::post('files', 'Common\FileController@upload')->name('files.upload');

    }
);
//Auth::routes();

Route::get('/', 'PagesController@index')->name('home');

Route::get('/catalog.html', 'CatalogController@index')->name('catalog.index');

Route::group([
    'prefix' => 'catalog',
    'as'     => 'catalog.',
],
    function () {

        Route::get('/product/{uri}.html', 'CatalogController@product')->name('product');
        Route::get('/{fulluri}.html', 'CatalogController@category')->where('fulluri', '[A-Za-z\_\-\/0-9\.]+')->name('category');

    });

Route::get('/contacts.html', array('as' => 'contacts.index', 'uses' => 'ContactsController@index'));
Route::post('/contacts.html', array('as' => 'contacts.send', 'uses' => 'ContactsController@send'));
Route::get('/certificates.html', array('as' => 'certificates.index', 'uses' => 'CertificatesController@index'));
Route::get('/normative-acts.html', array('as' => 'acts.index', 'uses' => 'ActsController@index'));
Route::get('/{fulluri}.html', array('as' => 'pages.page', 'uses' => 'PagesController@page'))->where('fulluri', '[A-Za-z\_\-\/0-9]+');
//Route::get('/', 'PagesController@index')->name('home');

app/Models/File.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class File extends Model
{
    use \App\Traits\ModelStatusTrait;

    const STATUS_ACTIVE   = 'active';
    const STATUS_INACTIVE = 'inactive';

    const FILES_DIRECTORY = 'files';

    public function getFile()
    {
        return self::FILES_DIRECTORY . '/' . $this->name;
    }

    public function getSize()
    {
        if(\Storage::disk('public')->exists($this->getFile()))
        {
            $size  = \Storage::disk('public')->getSize($this->getFile());
            $units = ['b', 'Kb', 'Mb', 'Gb', 'Tb', 'Pb', 'Eb', 'Zb', 'Yb'];
            $power = $size > 0 ? floor(log($size, 1024)) : 0;

            return number_format($size / pow(1024, $power), 0, '.', ',') . ' ' . $units[$power];
        }

        return '0 b';
    }

    public function getFileType()
    {
        if(\Storage::disk('public')->exists($this->getFile()))
        {
            $size  = \Storage::disk('public')->getSize($this->getFile());
            $units = ['b', 'Kb', 'Mb', 'Gb', 'Tb', 'Pb', 'Eb', 'Zb', 'Yb'];
            $power = $size > 0 ? floor(log($size, 1024)) : 0;

            return number_format($size / pow(1024, $power), 0, '.', ',') . ' ' . $units[$power];
        }

        return '0 b';
    }

}

app/Http/Controllers/Admin/Common/FileController.php
<?php

namespace App\Http\Controllers\Admin\Common;

use App\Http\Requests\Admin\Files\CreateFileRequest;
use App\Http\Requests\Admin\Files\UpdateFileRequest;
use App\Models\File;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Storage;


class FileController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $files = File::where(['owner_class' => $request->owner_class, 'owner_id' => $request->owner_id])->orderBy('sort')->get();
        return view('admin.files._list', [
            'files'       => $files,
            'owner_id'    => $request->owner_id,
            'owner_class' => $request->owner_class
        ])->render();
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return response()->json([
            'form'   => view('admin.files._form', ['file' => new File()])->render(),
            'action' => route('admin.files.store'),
            'method' => 'post',
            'title'  => __('admin.files.TTL_ADD_FILE'),
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  App\Http\Requests\Admin\Files\CreateFileRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateFileRequest $request)
    {
        $fileName = '';
        $fileType = '';
        if ($request->file('file.name'))
        {
            $fileName = $this->_saveFile($request);
            $fileType = $request->file('file.name')->getClientOriginalExtension();
        }

        $file              = new File();
        $file->name        = $fileName;
        $file->type        = $fileType;
        $file->owner_id    = $request->file['owner_id'];
        $file->owner_class = $request->file['owner_class'];
        $file->title       = $request->file['title'];
        $file->description = $request->file['description'];
        $file->sort        = $request->file['sort'];
        $file->status      = $request->file['status'];
        $file->save();

        return response()->json(['success' => __('admin.files.MSG_FILE_UPLOADED')]);

    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  File $file
     * @return \Illuminate\Http\Response
     */
    public function edit(File $file)
    {
        return response()->json([
            'form'   => view('admin.files._form', ['file' => $file])->render(),
            'action' => route('admin.files.update', ['file' => $file]),
            'method' => 'put',
            'title'  => __('admin.files.TTL_EDIT_FILE'),
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  App\Http\Requests\Admin\Files\UpdateFileRequest $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateFileRequest $request, File $file)
    {
        if ($request->file('file.name'))
        {
            $fileName = $this->_saveFile($request);
            $fileType = $request->file('file.name')->getClientOriginalExtension();
        }
        else
        {
            $fileName = $file->name;
            $fileType = $file->type;
        }

        $file->name        = $fileName;
        $file->type        = $fileType;
        $file->title       = $request->file['title'];
        $file->description = $request->file['description'];
        $file->sort        = $request->file['sort'];
        $file->status      = $request->file['status'];
        $file->save();

        return response()->json(['success' => __('admin.files.MSG_FILE_UPDATED')]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(File $file)
    {
        Storage::disk('public')->delete($file->getFile());
        $file->delete();

        return response()->json(['success' => __('admin.files.MSG_FILE_DELETED')]);
    }

    private function _saveFile($request)
    {
        $fileName = $request->file('file.name')->getClientOriginalName();
        $request->file('file.name')->storeAs(File::FILES_DIRECTORY, $fileName, 'public');

        return $fileName;
    }
}

resources/views/admin/files/_add-button.blade.php
<button type="button" class="btn btn-primary file-button"
        data-toggle="modal"
        data-target="#file-modal"
        data-owner_id="{{$owner_id}}"
        data-owner_class="{{$owner_class}}"
        data-get="{{route('admin.files.create')}}"><span
            class="fa fa-plus"></span> {{__('admin.files.TTL_ADD_FILE')}}
</button>

resources/views/admin/files/_form.blade.php
<div class="form-group{{ $errors->has('file.title') ? ' has-error' : ' has-success' }}">
    <label for="file_title">{{__('admin.files.ATR_TITLE')}}</label>
    <input type="text" id="file_title" name="file[title]"
           value="{{ old('file.title', $file->title) }}"
           class="form-control"
           placeholder="Enter File title"/>
    @if ($errors->has('file.title'))
        <span class="help-block"><strong>{{ $errors->first('file.title') }}</strong></span>
    @endif
</div>
<div class="form-group{{ $errors->has('file.description') ? ' has-error' : ' has-success' }}">
    <label for="file_description">{{__('admin.files.ATR_DESCRIPTION')}}</label>
    <textarea id="file_description" name="file[description]"
              class="form-control">{{ old('file.description', $file->description)}}</textarea>
    @if ($errors->has('file.description'))
        <span class="help-block"><strong>{{ $errors->first('file.description') }}</strong></span>
    @endif
</div>
<div class="form-group{{ $errors->has('file.name') ? ' has-error' : ' has-success' }}">
    <label for="file_name">{{__('admin.files.ATR_FILE')}}</label>
    <input type="file" id="file_name" name="file[name]" value="" class="form-control"/>
    @if ($errors->has('file.name'))
        <span class="help-block"><strong>{{ $errors->first('file.name') }}</strong></span>
    @endif
</div>
<div class="form-group{{ $errors->has('file.sort') ? ' has-error' : ' has-success' }}">
    <label for="file_sort">{{__('admin.ATR_SORT')}}</label>
    <input type="text" class="form-control" name="file[sort]" id="file_sort"
           value="{{ old('file.sort', $file->sort) }}"
           placeholder="Enter sort">
    @if ($errors->has('file.sort'))
        <span class="help-block"><strong>{{ $errors->first('file.sort') }}</strong></span>
    @endif
</div>
<div class="form-group{{ $errors->has('file.status') ? ' has-error' : ' has-success' }}">
    <label for="file_status">{{__('admin.ATR_STATUS')}}</label>
    <select class="form-control" name="file[status]" id="file_status">
        @foreach (\App\Models\File::statuses() as $status)
            <option value="{{ $status }}"
                    @if($status == $file->status) selected="selected" @endif>{{ __("status.$status") }}</option>
        @endforeach;
    </select>

    @if ($errors->has('file.status'))
        <span class="help-block"><strong>{{ $errors->first('file.status') }}</strong></span>
    @endif
</div>
<input type="hidden" id="type" name="file[type]" value="{{$file->type}}"/>
<input type="hidden" id="file_owner_id" name="file[owner_id]" value="{{$file->owner_id}}"/>
<input type="hidden" id="file_owner_class" name="file[owner_class]" value="{{$file->owner_class}}"/>

resources/views/admin/files/_list.blade.php
<div class="text-right">@include('admin.files._add-button', ['owner_id' => $owner_id, 'owner_class' => $owner_class])</div>
<table class="table table-bordered table-striped">
    <thead>
    <tr>
        <th>ID</th>
        <th>{{__('admin.files.ATR_FILENAME')}}</th>
        <th>{{__('admin.files.ATR_TYPE')}}</th>
        <th>{{__('admin.files.ATR_TITLE')}}</th>
        <th>{{__('admin.files.ATR_DESCRIPTION')}}</th>
        <th>{{__('admin.ATR_SORT')}}</th>
        <th>{{__('admin.ATR_STATUS')}}</th>
        <th>{{__('admin.ATR_CREATED_AT')}}</th>
        <th>{{__('admin.ATR_UPDATED_AT')}}</th>
        <th>{{__('admin.TTL_ACTIONS')}}</th>
    </tr>
    </thead>
    <tbody>

    @if(count($files) == 0)
        <tr>
            <td colspan="10">
                <div class="text-center">{{__('admin.files.TTL_NO_FILES')}}</div>
            </td>
        </tr>
    @endif

    @foreach($files as $file)
            <tr>
                <td>{{$file->id}}</td>
                <td>{{$file->name}}</td>
                <td>{{$file->type}}</td>
                <td>{{$file->title}}</td>
                <td>{{$file->description}}</td>
                <td>{{$file->sort}}</td>
                <td>{{$file->status}}</td>
                <td>{{$file->created_at}}</td>
                <td>{{$file->updated_at}}</td>
                <td>
                    <a href="#"
                       data-toggle="modal"
                       data-target="#file-modal"
                       data-get="{{route('admin.files.edit', $file->id)}}"
                       class="btn btn-xs btn-success"><span class="fa fa-edit"></span> {{__('admin.TTL_EDIT')}}</a>
                    <a href="#"
                       class="btn btn-xs btn-danger remove-file"
                       data-action="{{ route('admin.files.destroy', $file) }}"
                       ><span class="fa fa-remove"></span> {{__('admin.TTL_DELETE')}}</a>
                </td>
            </tr>
        @endforeach


    </tbody>

</table>
<div class="text-right">@include('admin.files._add-button', ['owner_id' => $owner_id, 'owner_class' => $owner_class])</div>

resources/views/admin/files/_modal_form.blade.php
<div class="modal fade" id="file-modal">
    <div class="modal-dialog">
        <div class="modal-content">
            <form action="/" method="post" enctype="multipart/form-data" id="file-form-modal">
                @csrf
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">{{__('admin.files.TTL_ADD_FILE')}}</h4>
                </div>
                <div class="modal-body">


                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default pull-left" data-dismiss="modal">{{__('admin.TTL_CLOSE')}}</button>
                    <button type="submit" class="btn btn-primary" id="modal-save">{{__('admin.TTL_SAVE')}}</button>
                </div>
            </form>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->
@section('scripts')
    <script>

        // Load form to modal
        $('#file-modal').on('show.bs.modal', function (event) {

            var button = $(event.relatedTarget)
            var modal = $(this);


            $.ajax({
                url: button.attr('data-get'),
                method: 'get',
                dataType: 'json',
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content'),
                    'Accept': 'application/json'
                },
                success: function (result) {


                    $('#modal-save').show();
                    modal.find('.modal-title').html(result.title);
                    modal.find('.modal-body').html(result.form);
                    modal.find('.modal-content form').attr('action', result.action);
                    modal.find('.modal-content form').attr('method', result.method);
                    if (button.attr('data-owner_id')) {
                        modal.find('#file_owner_id').val(button.attr('data-owner_id'));
                        modal.find('#file_owner_class').val(button.attr('data-owner_class'));
                    }

                }
            });

        });

        // Send form
        $('#modal-save').on('click', function (event) {
            event.stopPropagation();
            event.preventDefault();

            var form_data = new FormData();
            if ($('#file-form-modal').attr('method') == 'put') {
                form_data.append('_method', 'put');
            }

            if($('#file_name').prop('files')[0] != undefined)
            {
                form_data.append('file[name]', $('#file_name').prop('files')[0]);
            }

            form_data.append('file[title]', $('#file_title').val());
            form_data.append('file[description]', $('#file_description').val());
            form_data.append('file[sort]', $('#file_sort').val());
            form_data.append('file[status]', $('#file_status > option:selected').val());
            form_data.append('file[owner_id]', $('#file_owner_id').val());
            form_data.append('file[owner_class]', $('#file_owner_class').val());



            $('.modal-content form').find('.help-block').remove();
            $('.modal-content form').find('.form-group').removeClass('has-error');

            $.ajax({
                url: $('#file-form-modal').attr('action'),
                method: 'post',
                dataType: 'json',
                cache: false,
                contentType: false,
                processData: false,
                data: form_data,
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content'),
                    'Accept': 'application/json'
                },
                success: function (response) {

                    loadFilesList();
                    $('.modal-body').html(response.success);
                    $('#modal-save').hide();


                },
                error: function (xhr, status, response) {

                    var error = $.parseJSON(xhr.responseText);

                    if ($.isEmptyObject(error.errors) == false) {

                        $.each(error.errors, function (key, value) {

                            $('#' + key.replace(".", "_"))
                                .closest('.form-group')
                                .addClass('has-error')
                                .append('<span class="help-block"><strong>' + value + '</strong></span>');
                        });
                    }

                }
            });

        });

        // Remove file
        $('body').on('click', '.remove-file', function(event){

            event.stopPropagation();
            event.preventDefault();
            if(confirm('Are you sure?'))
            {
                var form_data = new FormData();
                form_data.append('_method', 'delete');

                $.ajax({
                    url: $(this).attr('data-action'),
                    method: 'post',
                    dataType: 'json',
                    cache: false,
                    contentType: false,
                    processData: false,
                    data: form_data,
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content'),
                        'Accept': 'application/json'
                    },
                    success: function (response) {

                        loadFilesList();
                        alert(response.success);
                    }
                });
            }


        });

        // Load files list
        function loadFilesList()
        {
            $.ajax({
                url: '{{route('admin.files')}}',
                method: 'get',
                dataType: 'html',
                cache: false,
                contentType: false,
                data: 'owner_id='+$('.file-button').attr('data-owner_id')+'&owner_class='+$('.file-button').attr('data-owner_class'),
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content'),
                    'Accept': 'application/json'
                },
                success: function (response) {
                    $('#tab_files').html(response);
                }
            });
        }
    </script>
@endsection

resources/views/admin/files/_show_files.blade.php
<dl class="dl-horizontal">
    <dt>{{__('admin.files.TTL_FILES')}}</dt>
    <dd>
        <table class="table table-bordered table-striped">
            <thead>
            <tr>
                <th>ID</th>
                <th>{{__('admin.files.ATR_FILENAME')}}</th>
                <th>{{__('admin.files.ATR_TYPE')}}</th>
                <th>{{__('admin.files.ATR_TITLE')}}</th>
                <th>{{__('admin.files.ATR_DESCRIPTION')}}</th>
                <th>{{__('admin.ATR_SORT')}}</th>
                <th>{{__('admin.ATR_STATUS')}}</th>
                <th>{{__('admin.ATR_CREATED_AT')}}</th>
                <th>{{__('admin.ATR_UPDATED_AT')}}</th>
            </tr>
            </thead>
            <tbody>

            @if(count($files) == 0)
                <tr>
                    <td colspan="10">
                        <div class="text-center">{{__('admin.files.TTL_NO_FILES')}}</div>
                    </td>
                </tr>
            @endif

            @foreach($files as $file)
                <tr>
                    <td>{{$file->id}}</td>
                    <td>{{$file->name}}</td>
                    <td>{{$file->type}}</td>
                    <td>{{$file->title}}</td>
                    <td>{{$file->description}}</td>
                    <td>{{$file->sort}}</td>
                    <td>{{$file->status}}</td>
                    <td>{{$file->created_at}}</td>
                    <td>{{$file->updated_at}}</td>
                </tr>
            @endforeach


            </tbody>

        </table>
    </dd>
</dl>