routes/web.php
<?php

Route::get('/', function () {
    return view('welcome');
});

Route::get('admin/login', 'Admin\Auth\LoginController@showLoginForm')->name('admin.login');
Route::post('admin/login', 'Admin\Auth\LoginController@login');

Route::group(
    [
        'prefix'     => 'admin',
        'as'         => 'admin.',
        'namespace'  => 'Admin',
        'middleware' => [
            'auth',
            'can:admin-panel'
        ],
    ],
    function () {

        Route::get('/', 'DashboardController@index')->name('dashboard');

        Route::post('logout', 'Auth\LoginController@logout')->name('logout');

        // Route::resource('user', 'UserController')->name('index', 'user');
        Route::resource('user', 'Users\UserController')->name('index', 'user');
        Route::resource('page', 'Pages\PageController')->name('index', 'page');
        Route::resource('category', 'Catalog\CategoryController')->name('index', 'category');
        Route::resource('product', 'Catalog\ProductController')->name('index', 'product');
        Route::resource('certificate', 'Certificates\CertificateController')->name('index', 'certificate');


        Route::resource('files', 'Common\FileController')->name('index', 'files');

        //Route::get('files/create', 'Common\FileController@create')->name('files.create');
        //Route::post('files/create', 'Common\FileController@store')->name('files.store');
        //Route::get('files/{id}/edit', 'Common\FileController@edit')->name('files.edit');
        //Route::post('files/{id}/edit', 'Common\FileController@update')->name('files.update');


        //Route::post('files/create', 'Common\FileController@store')->name('store', 'files');

        //Route::get('files', 'Common\FileController@index')->name('files.list');
        //Route::post('files', 'Common\FileController@upload')->name('files.upload');

    }
);
//Auth::routes();

Route::get('/', 'PagesController@index')->name('home');

Route::get('/catalog.html', 'CatalogController@index')->name('catalog.index');

Route::group([
    'prefix' => 'catalog',
    'as'     => 'catalog.',
],
    function () {

        Route::get('/product/{uri}.html', 'CatalogController@product')->name('product');
        Route::get('/{fulluri}.html', 'CatalogController@category')->where('fulluri', '[A-Za-z\_\-\/0-9\.]+')->name('category');

    });

Route::get('/contacts.html', array('as' => 'contacts.index', 'uses' => 'ContactsController@index'));
Route::post('/contacts.html', array('as' => 'contacts.send', 'uses' => 'ContactsController@send'));
Route::get('/certificates.html', array('as' => 'certificates.index', 'uses' => 'CertificatesController@index'));
Route::get('/normative-acts.html', array('as' => 'acts.index', 'uses' => 'ActsController@index'));
Route::get('/{fulluri}.html', array('as' => 'pages.page', 'uses' => 'PagesController@page'))->where('fulluri', '[A-Za-z\_\-\/0-9]+');
//Route::get('/', 'PagesController@index')->name('home');

resources/views/admin/pages/page/_form.blade.php
<form action="{{$action}}" method="post">
    @csrf
    @if(isset($method) && $method == 'put')
        @method('PUT')
    @endif
    <div class="box-body">

    @include('admin.page_elements._errors_list')

    <!-- Custom Tabs -->
        <div class="nav-tabs-custom">
            <ul class="nav nav-tabs">
                <li class="active"><a href="#tab_page" data-toggle="tab">{{__('admin.pages.TTL_PAGE')}}</a></li>
                <li><a href="#tab_meta" data-toggle="tab">{{__('admin.meta.TTL_META')}}</a></li>
                @if($mode != 'create')
                    <li><a href="#tab_files" data-toggle="tab">{{__('admin.files.TTL_FILES')}}</a></li>
                @endif
            </ul>
            <div class="tab-content">
                <div class="tab-pane active" id="tab_page">


                    <div class="form-group{{ $errors->has('name') ? ' has-error' : ' has-success' }}">
                        <label for="name">{{__('admin.pages.ATR_NAME')}}</label>
                        <input type="text" id="name" name="name" value="{{ old('name', $page->name) }}"
                               class="form-control"
                               placeholder=""/>
                        @if ($errors->has('name'))
                            <span class="help-block"><strong>{{ $errors->first('name') }}</strong></span>
                        @endif
                    </div>
                    <div class="form-group{{ $errors->has('parent_id') ? ' has-error' : ' has-success' }}">
                        <label for="parent_id">{{__('admin.pages.ATR_PARENT_PAGE')}}</label>
                        <select class="form-control" name="parent_id" id="parent_id">
                            <option value="0" @if($page->parent_id == 0) selected @endif>/</option>
                            @foreach ($tree as $page_id => $item)
                                <option value="{{ $page_id }}"
                                        @if($page->parent_id == $page_id) selected @endif>{{ $item['offset']}}{{ $item['name']}}</option>
                            @endforeach
                        </select>

                        @if ($errors->has('parent_id'))
                            <span class="help-block"><strong>{{ $errors->first('parent_id') }}</strong></span>
                        @endif
                    </div>
                    <div class="form-group{{ $errors->has('uri') ? ' has-error' : ' has-success' }}">
                        <label for="name">{{__('admin.pages.ATR_URI')}}</label>
                        <input type="text" id="uri" name="uri" value="{{ old('uri', $page->uri) }}" class="form-control"
                               placeholder=""/>
                        @if ($errors->has('uri'))
                            <span class="help-block"><strong>{{ $errors->first('uri') }}</strong></span>
                        @endif
                    </div>
                    <div class="form-group{{ $errors->has('content') ? ' has-error' : ' has-success' }}">
                        <label for="name">{{__('admin.pages.ATR_CONTENT')}}</label>
                        <textarea id="content" name="content" class="form-control htmleditor">{{ old('content', $page->content) }}</textarea>
                        @if ($errors->has('content'))
                            <span class="help-block"><strong>{{ $errors->first('content') }}</strong></span>
                        @endif
                    </div>
                    <div class="form-group{{ $errors->has('menu') ? ' has-error' : ' has-success' }}">
                        <label for="">{{__('admin.pages.ATR_DISPLAY_IN_MENU')}}</label>

                        @foreach($menus as $menu)
                            @php($checked = '')
                            @if(old('menu'))

                                @foreach(old('menu') as $pm)
                                    @if($pm == $menu->id)
                                        @php($checked = 'checked')
                                    @endif
                                @endforeach

                            @elseif($page->menus)

                                @foreach($page->menus as $pm)
                                    @if($pm->id == $menu->id)
                                        @php($checked = 'checked')
                                    @endif
                                @endforeach

                            @endif
                            <div class="checkbox">
                                <label for="menu_{{$menu->id}}">
                                    <input type="checkbox" name="menu[]" value="{{$menu->id}}"
                                           id="menu_{{$menu->id}}" {{$checked}}/>
                                    {{$menu->name}}
                                </label>
                            </div>
                        @endforeach
                    </div>
                    <div class="form-group{{ $errors->has('sort') ? ' has-error' : ' has-success' }}">
                        <label for="sort">{{__('admin.ATR_SORT')}}</label>
                        <input type="text" class="form-control" name="sort" id="sort"
                               value="{{ old('sort', $page->sort) }}"
                               placeholder="">
                        @if ($errors->has('sort'))
                            <span class="help-block"><strong>{{ $errors->first('sort') }}</strong></span>
                        @endif
                    </div>
                    <div class="form-group{{ $errors->has('status') ? ' has-error' : ' has-success' }}">
                        <label for="status">{{__('admin.ATR_STATUS')}}</label>
                        <select class="form-control" name="status" id="status">
                            @foreach (\App\Models\Page::statuses() as $status)
                                <option value="{{ $status }}"
                                        @if($status == $page->status) selected="selected" @endif>{{ __("status.$status") }}</option>
                            @endforeach;
                        </select>

                        @if ($errors->has('status'))
                            <span class="help-block"><strong>{{ $errors->first('status') }}</strong></span>
                        @endif
                    </div>


                </div>
                <!-- /.tab-pane -->
                <div class="tab-pane" id="tab_meta">
                    @include('admin.meta._form', ['meta' => $page->getMeta()])
                </div>
                <!-- /.tab-pane -->
                @if($mode != 'create')
                    <div class="tab-pane" id="tab_files">

                        @include('admin.files._list', ['files' => $page->getFiles(),
                        'owner_id' => $page->id,
                        'owner_class' => get_class($page)
                        ])

                    </div>
            @endif
            <!-- /.tab-pane -->
            </div>
            <!-- /.tab-content -->
        </div>
        <!-- nav-tabs-custom -->

    </div>
    <!-- /.box-body -->


    <div class="box-footer">
        @include('admin.page_elements._buttons', ['mode' => $mode, 'cancel_route' => 'admin.page'])
    </div>
</form>
@include('admin.files._modal_form')

resources/views/admin/pages/page/create.blade.php
@extends('admin.layouts.onecolumn')

@section('header', __('admin.pages.TTL_NEW_PAGE'))
@section('breadcrumbs', Breadcrumbs::render())
@section('main_block_content')

    <div class="row">
        <div class="col-xs-12">
            <div class="box">

                @include('admin.pages.page._form', [
                'mode' => 'create',
                'page' => $page,
                'tree' => $tree,
                'menus' => $menus,
                'action' => route('admin.page.store')])

            </div>
        </div>
    </div>

@endsection

resources/views/admin/pages/page/edit.blade.php
@extends('admin.layouts.onecolumn')

@section('header', __('admin.pages.TTL_EDIT_PAGE'))
@section('breadcrumbs', Breadcrumbs::render())
@section('main_block_content')
    <!-- Main content -->

    <div class="row">
        <div class="col-xs-12">
            <div class="box">

                @include('admin.pages.page._form', [
                'method' => 'put',
                'mode' => 'update',
                'page' => $page,
                'tree' => $tree,
                'menus' => $menus,
                'action' => route('admin.page.update', ['page' => $page])
                ])

            </div>
        </div>
    </div>

@endsection

resources/views/admin/pages/page/index.blade.php
@extends('admin.layouts.onecolumn')

@section('header', __('admin.pages.TTL_PAGES'))
@section('breadcrumbs', Breadcrumbs::render())
@section('main_block_content')

    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <div class="text-right"><a href="{{route('admin.page.create')}}" class="btn btn-primary"><span
                                class="fa fa-plus"></span> {{__('admin.pages.TTL_ADD_NEW_PAGE')}}</a></div>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <table id="table1" class="table table-bordered table-striped">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>{{__('admin.pages.ATR_NAME')}}</th>
                            <th>{{__('admin.pages.ATR_URI')}}</th>
                            <th>{{__('admin.TTL_SORT')}}</th>
                            <th>{{__('admin.TTL_STATUS')}}</th>
                            <th>{{__('admin.TTL_CREATED_AT')}}</th>
                            <th>{{__('admin.TTL_UPDATED_AT')}}</th>
                            <th>{{__('admin.TTL_ACTIONS')}}</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($pages as $page)
                            <tr>
                                <td>{{$page->id}}</td>
                                <td>{{$page->name}}</td>
                                <td>{{$page->fulluri}}</td>
                                <td>{{$page->sort}}</td>
                                <td>{{$page->status}}</td>
                                <td>{{$page->created_at}}</td>
                                <td>{{$page->updated_at}}</td>
                                <td>
                                    <a href="{{route('admin.page.show', $page->id)}}"
                                       class="btn btn-xs btn-info"><span
                                            class="fa fa-eye"></span> {{__('admin.TTL_VIEW')}}</a>
                                    <a href="{{route('admin.page.edit', $page->id)}}"
                                       class="btn btn-xs btn-success"><span
                                            class="fa fa-edit"></span> {{__('admin.TTL_EDIT')}}</a>
                                    <form method="POST" action="{{ route('admin.page.destroy', $page) }}"
                                          class="inline">
                                        @csrf
                                        @method('DELETE')
                                        <button class="btn btn-xs btn-danger" onclick="return confirm('{{__('admin.TTL_DELETE_SURE')}}')"><span
                                                class="fa fa-remove"></span> {{__('admin.TTL_DELETE')}}
                                        </button>
                                    </form>

                                </td>
                            </tr>
                        @endforeach

                        </tbody>
                        <tfoot>
                        <tr>
                            <th>ID</th>
                            <th>{{__('admin.pages.ATR_NAME')}}</th>
                            <th>{{__('admin.pages.ATR_URI')}}</th>
                            <th>{{__('admin.TTL_SORT')}}</th>
                            <th>{{__('admin.TTL_STATUS')}}</th>
                            <th>{{__('admin.TTL_CREATED_AT')}}</th>
                            <th>{{__('admin.TTL_UPDATED_AT')}}</th>
                            <th>{{__('admin.TTL_ACTIONS')}}</th>
                        </tr>
                        </tfoot>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
    </div>

@endsection

resources/views/admin/pages/page/show.blade.php
@extends('admin.layouts.onecolumn')

@section('header', __('admin.pages.TTL_VIEW_PAGE'))
@section('breadcrumbs', Breadcrumbs::render())
@section('main_block_content')
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <!-- /.box-header -->
                <div class="box-body">
                    <div class="text-right">
                        <a href="{{route('admin.page')}}" class="btn btn-info"><span
                                    class="fa fa-list"></span> {{__('admin.TTL_BACK_TO_LIST')}}</a>
                        <a href="{{route('admin.page.edit', $page->id)}}" class="btn btn-success"><span
                                    class="fa fa-edit"></span> {{__('admin.TTL_EDIT')}}</a>
                        <form method="POST" action="{{ route('admin.page.destroy', $page) }}" class="inline">
                            @csrf
                            @method('DELETE')
                            <button class="btn btn-danger" onclick="return confirm('{{__('admin.TTL_DELETE_SURE')}}')"><span
                                        class="fa fa-remove"></span> {{__('admin.TTL_DELETE')}}
                            </button>
                        </form>
                        <a href="{{route('admin.page.create')}}" class="btn btn-primary"><span
                                    class="fa fa-plus"></span> {{__('admin.pages.TTL_ADD_NEW_PAGE')}}</a>
                    </div>
                    <!-- Main content -->
                    <dl class="dl-horizontal">
                        <dt>ID</dt>
                        <dd>{{$page->id}}</dd>

                        <dt>{{__('admin.pages.ATR_NAME')}}</dt>
                        <dd>{{$page->name}}</dd>

                        <dt>{{__('admin.pages.ATR_URI')}}</dt>
                        <dd>{{$page->uri}}</dd>

                        <dt>{{__('admin.pages.ATR_CONTENT')}}</dt>
                        <dd>{{$page->content}}</dd>

                        <dt>{{__('admin.ATR_SORT')}}</dt>
                        <dd>{{$page->sort}}</dd>

                        <dt>{{__('admin.ATR_STATUS')}}</dt>
                        <dd>{{$page->status}}</dd>
                    </dl>

                    @include('admin.meta._show_meta', ['item' => $page])
                    @include('admin.files._show_files', ['files' => $page->getFiles()])

                </div>
            </div>
        </div>
    </div>
@endsection