routes/web.php
<?php

Route::get('/', function () {
    return view('welcome');
});

Route::get('admin/login', 'Admin\Auth\LoginController@showLoginForm')->name('admin.login');
Route::post('admin/login', 'Admin\Auth\LoginController@login');

Route::group(
    [
        'prefix'     => 'admin',
        'as'         => 'admin.',
        'namespace'  => 'Admin',
        'middleware' => [
            'auth',
            'can:admin-panel'
        ],
    ],
    function () {

        Route::get('/', 'DashboardController@index')->name('dashboard');

        Route::post('logout', 'Auth\LoginController@logout')->name('logout');

        // Route::resource('user', 'UserController')->name('index', 'user');
        Route::resource('user', 'Users\UserController')->name('index', 'user');
        Route::resource('page', 'Pages\PageController')->name('index', 'page');
        Route::resource('category', 'Catalog\CategoryController')->name('index', 'category');
        Route::resource('product', 'Catalog\ProductController')->name('index', 'product');
        Route::resource('certificate', 'Certificates\CertificateController')->name('index', 'certificate');


        Route::resource('files', 'Common\FileController')->name('index', 'files');

        //Route::get('files/create', 'Common\FileController@create')->name('files.create');
        //Route::post('files/create', 'Common\FileController@store')->name('files.store');
        //Route::get('files/{id}/edit', 'Common\FileController@edit')->name('files.edit');
        //Route::post('files/{id}/edit', 'Common\FileController@update')->name('files.update');


        //Route::post('files/create', 'Common\FileController@store')->name('store', 'files');

        //Route::get('files', 'Common\FileController@index')->name('files.list');
        //Route::post('files', 'Common\FileController@upload')->name('files.upload');

    }
);
//Auth::routes();

Route::get('/', 'PagesController@index')->name('home');

Route::get('/catalog.html', 'CatalogController@index')->name('catalog.index');

Route::group([
    'prefix' => 'catalog',
    'as'     => 'catalog.',
],
    function () {

        Route::get('/product/{uri}.html', 'CatalogController@product')->name('product');
        Route::get('/{fulluri}.html', 'CatalogController@category')->where('fulluri', '[A-Za-z\_\-\/0-9\.]+')->name('category');

    });

Route::get('/contacts.html', array('as' => 'contacts.index', 'uses' => 'ContactsController@index'));
Route::post('/contacts.html', array('as' => 'contacts.send', 'uses' => 'ContactsController@send'));
Route::get('/certificates.html', array('as' => 'certificates.index', 'uses' => 'CertificatesController@index'));
Route::get('/normative-acts.html', array('as' => 'acts.index', 'uses' => 'ActsController@index'));
Route::get('/{fulluri}.html', array('as' => 'pages.page', 'uses' => 'PagesController@page'))->where('fulluri', '[A-Za-z\_\-\/0-9]+');
//Route::get('/', 'PagesController@index')->name('home');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Admin/Users/UserController.php
<?php

namespace App\Http\Controllers\Admin\Users;

use App\Models\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();
        return view('admin.user.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.user.create', ['user' => new User()]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Validation\ValidationException
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|string|max:255',
            'email' => 'required|email|string|max:255|unique:users',
            'password' => 'required|string|max:255',
            'password_confirmation' => 'required|same:password',
        ]);

        $user = User::create([
            'name' => $request->name,
            'email' => $request->email,
            'password' => \Hash::make($request->password),
        ]);

        flash(__('admin.users.MSG_USER_CREATED'))->success();

        return admin_redirect('admin.user', $user);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\User $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        return view('admin.user.show', ['user' => $user]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\User $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('admin.user.edit', ['user' => $user]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Models\User $user
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Validation\ValidationException
     */
    public function update(Request $request, User $user)
    {
        $this->validate($request, [
            'name' => 'required|string|max:255',
            'email' => 'required|email|string|max:255|unique:users,id,' . $user->id,
        ]);

        $user->update(['name' => $request->name, 'email' => $request->email]);

        if(!empty($request->password))
        {
            $this->validate($request, [
                'password' => 'required|string|max:255',
                'password_confirmation' => 'required|same:password',
            ]);

            $user->update(['password' => \Hash::make($request->password)]);
        }

        flash(__('admin.users.MSG_USER_UPDATED'))->success();

        return admin_redirect('admin.user', $user);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\User $user
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function destroy(User $user)
    {
        $user->delete();
        flash(__('admin.users.MSG_USER_DELETED'))->success();
        return redirect()->route('admin.user');
    }
}

resources/views/admin/user/_form.blade.php
<form action="{{$action}}" method="post">
    @csrf
    @if(isset($method) && $method == 'put')
        @method('PUT')
    @endif
    <div class="box-body">
        <div class="form-group{{ $errors->has('name') ? ' has-error' : ' has-success' }}">
            <label for="user_name">{{__('admin.users.ATR_NAME')}}</label>
            <input type="text" id="user_name" name="name" value="{{ old('name', $user->name) }}" class="form-control" placeholder="" />
            @if ($errors->has('name'))
                <span class="help-block"><strong>{{ $errors->first('name') }}</strong></span>
            @endif
        </div>
        <div class="form-group{{ $errors->has('email') ? ' has-error' : ' has-success' }}">
            <label for="email">{{__('admin.users.ATR_EMAIL')}}</label>
            <input type="email" class="form-control" name="email" id="email" value="{{ old('email', $user->email) }}" placeholder="">
            @if ($errors->has('email'))
                <span class="help-block"><strong>{{ $errors->first('email') }}</strong></span>
            @endif
        </div>
        <div class="form-group{{ $errors->has('password') ? ' has-error' : ' has-success' }}">
            <label for="password">{{__('admin.users.ATR_PASSWORD')}}</label>
            <input type="password" class="form-control" name="password" id="password" placeholder="">
            @if ($errors->has('password'))
                <span class="help-block"><strong>{{ $errors->first('password') }}</strong></span>
            @endif
        </div>
        <div class="form-group{{ $errors->has('password_confirmation') ? ' has-error' : ' has-success' }}">
            <label for="password">{{__('admin.users.ATR_CONFIRM_PASSWORD')}}</label>
            <input type="password" class="form-control" name="password_confirmation" id="password_confirm" placeholder="">
            @if ($errors->has('password_confirmation'))
                <span class="help-block"><strong>{{ $errors->first('password_confirmation') }}</strong></span>
            @endif
        </div>
    </div>
    <!-- /.box-body -->

    <div class="box-footer">
        @include('admin.page_elements._buttons', ['mode' => $mode, 'cancel_route' => 'admin.user'])
    </div>
</form>

resources/views/admin/user/create.blade.php
@extends('admin.layouts.onecolumn')

@section('header', __('admin.users.TTL_NEW_USER'))
@section('breadcrumbs', Breadcrumbs::render())
@section('main_block_content')

    <div class="row">
        <div class="col-xs-12">
            <div class="box">

                @include('admin.user._form', ['user' => $user, 'action' => route('admin.user.store'), 'mode' => 'create'])

            </div>
        </div>
    </div>

@endsection

resources/views/admin/user/edit.blade.php
@extends('admin.layouts.onecolumn')

@section('header', __('admin.users.TTL_EDIT_USER'))
@section('breadcrumbs', Breadcrumbs::render())
@section('main_block_content')
    <!-- Main content -->

    <div class="row">
        <div class="col-xs-12">
            <div class="box">

                @include('admin.user._form', ['method' => 'put',
                'user' => $user,
                'mode' => 'update',
                'action' => route('admin.user.update', ['user' => $user])])

            </div>
        </div>
    </div>

@endsection

resources/views/admin/user/index.blade.php
@extends('admin.layouts.onecolumn')

@section('header', __('admin.users.TTL_USERS'))
@section('breadcrumbs', Breadcrumbs::render())
@section('main_block_content')

<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
                <div class="text-right"><a href="{{route('admin.user.create')}}" class="btn btn-primary"><span
                            class="fa fa-plus"></span> {{__('admin.users.TTL_ADD_NEW_USER')}}</a></div>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <table id="table1" class="table table-bordered table-striped">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>{{__('admin.users.ATR_NAME')}}</th>
                        <th>{{__('admin.users.ATR_EMAIL')}}</th>
                        <th>{{__('admin.ATR_CREATED_AT')}}</th>
                        <th>{{__('admin.ATR_UPDATED_AT')}}</th>
                        <th>{{__('admin.ATR_ACTIONS')}}</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($users as $user)
                        <tr>
                            <td>{{$user->id}}</td>
                            <td>{{$user->name}}</td>
                            <td>{{$user->email}}</td>
                            <td>{{$user->created_at}}</td>
                            <td>{{$user->updated_at}}</td>
                            <td>
                                <a href="{{route('admin.user.show', $user->id)}}" class="btn btn-xs btn-info"><span
                                        class="fa fa-eye"></span> {{__('admin.TTL_VIEW')}}</a>
                                <a href="{{route('admin.user.edit', $user->id)}}" class="btn btn-xs btn-success"><span
                                        class="fa fa-edit"></span> {{__('admin.TTL_EDIT')}}</a>
                                <form method="POST" action="{{ route('admin.user.destroy', $user) }}" class="inline">
                                    @csrf
                                    @method('DELETE')
                                    <button class="btn btn-xs btn-danger" onclick="return confirm('{{__('admin.TTL_DELETE_SURE')}}')"><span
                                            class="fa fa-remove"></span> {{__('admin.TTL_DELETE')}}
                                    </button>
                                </form>

                            </td>
                        </tr>
                    @endforeach

                    </tbody>
                    <tfoot>
                    <tr>
                        <th>ID</th>
                        <th>{{__('admin.users.ATR_NAME')}}</th>
                        <th>{{__('admin.users.ATR_EMAIL')}}</th>
                        <th>{{__('admin.ATR_CREATED_AT')}}</th>
                        <th>{{__('admin.ATR_UPDATED_AT')}}</th>
                        <th>{{__('admin.ATR_ACTIONS')}}</th>
                    </tr>
                    </tfoot>
                </table>
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>
</div>

@endsection

resources/views/admin/user/show.blade.php
@extends('admin.layouts.onecolumn')

@section('header', __('admin.users.TTL_VIEW_USER'))
@section('breadcrumbs', Breadcrumbs::render())
@section('main_block_content')
    <div class="row">
        <div class="col-xs-12">
            <div class="box">

                <div class="box-body">
                    <div class="text-right">
                        <a href="{{route('admin.user')}}" class="btn btn-info"><span
                                class="fa fa-list"></span> {{__('admin.TTL_BACK_TO_LIST')}}</a>
                        <a href="{{route('admin.user.edit', $user->id)}}" class="btn btn-success"><span
                                class="fa fa-edit"></span> {{__('admin.TTL_EDIT')}}</a>
                        <form method="POST" action="{{ route('admin.user.destroy', $user) }}" class="inline">
                            @csrf
                            @method('DELETE')
                            <button class="btn btn-danger" onclick="return confirm('{{__('admin.TTL_DELETE_SURE')}}')"><span
                                    class="fa fa-remove"></span> {{__('admin.TTL_DELETE')}}
                            </button>
                        </form>
                        <a href="{{route('admin.user.create')}}" class="btn btn-primary"><span
                                class="fa fa-plus"></span> {{__('admin.users.TTL_ADD_NEW_USER')}}</a>
                    </div>
                    <!-- Main content -->
                    <dl class="dl-horizontal">
                        <dt>ID</dt>
                        <dd>{{$user->id}}</dd>

                        <dt>{{__('admin.users.ATR_NAME')}}</dt>
                        <dd>{{$user->name}}</dd>

                        <dt>{{__('admin.users.ATR_EMAIL')}}</dt>
                        <dd>{{$user->email}}</dd>

                        {{--<dt>{{__('admin.ATR_STATUS')}}</dt>
                        <dd>{{$user->status}}</dd>--}}
                    </dl>
                </div>
            </div>
        </div>
    </div>
@endsection